# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ============================================================================
# Team Role Bindings - User Access Control
# ============================================================================

# QA Team - Viewer access to default and qa namespaces
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qa-team-default-access
  namespace: default
  labels:
    rbac.authorization.k8s.io/team-name: qa
    app.kubernetes.io/part-of: online-boutique
    app.kubernetes.io/component: team-rbac
  annotations:
    description: "QA team viewer access to default namespace"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: team-viewer
subjects:
- kind: User
  name: asdutoit@gmail.com  # Replace with actual QA team members
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qa-team-qa-access
  namespace: qa
  labels:
    rbac.authorization.k8s.io/team-name: qa
    app.kubernetes.io/part-of: online-boutique
    app.kubernetes.io/component: team-rbac
  annotations:
    description: "QA team viewer access to qa namespace"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: team-viewer
subjects:
- kind: User
  name: asdutoit@gmail.com  # Replace with actual QA team members
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qa-team-staging-access
  namespace: staging
  labels:
    rbac.authorization.k8s.io/team-name: qa
    app.kubernetes.io/part-of: online-boutique
    app.kubernetes.io/component: team-rbac
  annotations:
    description: "QA team viewer access to staging namespace"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: team-viewer
subjects:
- kind: User
  name: asdutoit@gmail.com  # Replace with actual QA team members
  apiGroup: rbac.authorization.k8s.io

---
# Development Team - Editor access to default, dev, and staging
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-team-default-access
  namespace: default
  labels:
    rbac.authorization.k8s.io/team-name: dev
    app.kubernetes.io/part-of: online-boutique
    app.kubernetes.io/component: team-rbac
  annotations:
    description: "Development team edit access to default namespace"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: team-editor
subjects:
- kind: User
  name: asdutoit@gmail.com  # Replace with actual dev team members
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-team-dev-access
  namespace: dev
  labels:
    rbac.authorization.k8s.io/team-name: dev
    app.kubernetes.io/part-of: online-boutique
    app.kubernetes.io/component: team-rbac
  annotations:
    description: "Development team edit access to dev namespace"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: team-editor
subjects:
- kind: User
  name: asdutoit@gmail.com  # Replace with actual dev team members
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-team-staging-access
  namespace: staging
  labels:
    rbac.authorization.k8s.io/team-name: dev
    app.kubernetes.io/part-of: online-boutique
    app.kubernetes.io/component: team-rbac
  annotations:
    description: "Development team edit access to staging namespace"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: team-editor
subjects:
- kind: User
  name: asdutoit@gmail.com  # Replace with actual dev team members
  apiGroup: rbac.authorization.k8s.io

---
# DevOps Team - Admin access to default, dev, staging, and prod
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-team-default-access
  namespace: default
  labels:
    rbac.authorization.k8s.io/team-name: devops
    app.kubernetes.io/part-of: online-boutique
    app.kubernetes.io/component: team-rbac
  annotations:
    description: "DevOps team admin access to default namespace"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: team-admin
subjects:
- kind: User
  name: asdutoit@gmail.com  # Replace with actual DevOps team members
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-team-dev-access
  namespace: dev
  labels:
    rbac.authorization.k8s.io/team-name: devops
    app.kubernetes.io/part-of: online-boutique
    app.kubernetes.io/component: team-rbac
  annotations:
    description: "DevOps team admin access to dev namespace"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: team-admin
subjects:
- kind: User
  name: asdutoit@gmail.com  # Replace with actual DevOps team members
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-team-staging-access
  namespace: staging
  labels:
    rbac.authorization.k8s.io/team-name: devops
    app.kubernetes.io/part-of: online-boutique
    app.kubernetes.io/component: team-rbac
  annotations:
    description: "DevOps team admin access to staging namespace"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: team-admin
subjects:
- kind: User
  name: asdutoit@gmail.com  # Replace with actual DevOps team members
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-team-prod-access
  namespace: prod
  labels:
    rbac.authorization.k8s.io/team-name: devops
    app.kubernetes.io/part-of: online-boutique
    app.kubernetes.io/component: team-rbac
  annotations:
    description: "DevOps team admin access to prod namespace"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: team-admin
subjects:
- kind: User
  name: asdutoit@gmail.com  # Replace with actual DevOps team members
  apiGroup: rbac.authorization.k8s.io

---
# Platform Team - Cluster-wide admin access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-team-cluster-admin
  labels:
    rbac.authorization.k8s.io/team-name: platform
    app.kubernetes.io/part-of: online-boutique
    app.kubernetes.io/component: team-rbac
  annotations:
    description: "Platform engineering team cluster-wide admin access"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: team-platform
subjects:
- kind: User
  name: asdutoit@gmail.com  # Replace with actual platform team members
  apiGroup: rbac.authorization.k8s.io